### ISSUE TITLE
사용자에게서 4자리 숫자 입력받기

### ISSUE THREAD

**Issue by HENOZIWD** [Jang-One/Bulls-Cows#2]
## Description

무작위로 생성된 4자리 숫자와 비교하기 위해 사용자에게서 4자리 숫자를 입력받습니다.

## Tasks

- [x] `input()` 함수를 통해 사용자에게서 4자리 숫자 입력받기
- [x] 4자리 숫자가 아닌 입력을 받으면 다시 입력받도록 하기
- [x] 중복된 숫자가 있다면 다시 입력받도록 하기
