### ISSUE TITLE
Generate random numbers

### ISSUE THREAD

**Issue by harin9** [Jang-One/Bulls-Cows#4]
## Description

Generate 4 numbers randomly.

## Tasks

- [x] import random module
- [x] generate 4 numbers randomly
- [x] return by list

## References
